{Arrow_show_time: 1, Break_between_fix_and_arrow: 1, Experiment_type: true, Fix_time: 1,
  Number_of_experiment_blocks: 1, Number_of_experiment_trials: 4, Number_of_training_trials: 4,
  Observer: true, Ophthalmic_procedure: false, Percent_of_trials_with_stop: 25, Resp_time: 1,
  Start_wait_to_stop: 1, Stop_show_time: 1, screen_color: true}
