Arrow_show_time: 1
Break_between_fix_and_arrow: 1
Fix_time: 1
Keys: [lctrl, rctrl]
Number_of_experiment_blocks: 1
Number_of_experiment_trials: 4
Number_of_training_trials: 4
Observer: Mis
Ophthalmic_procedure: false
Percent_of_trials_with_stop: 25
Possible_wait_to_stop: [1]
Resp_time: 2
Rest_time: 1
Rest_time_jitter: 1
Screen_color: 1
Send_EEG_trigg: false
Send_Nirs_trigg: false
Start_wait_to_stop: 1
Stop_show_time: 1
Text_size: 1
